title: Vincent Wayuga
description: "my web"
url: "https://Vinidah.github.io"

logo:
  path: "/assets/img/m-icon-blue-on-white.png"
  width: 300
  height: 300

image: "/assets/img/writings.jpg"
theme_color: "#000000"

author:
  name: Vincent Wayuga
  email: vincent.ogweno@aims.ac.rw
  uri: https://Vinidah.github.io
  avatar: "/assets/img/m-icon-white-on-blue.png"
  bio: "Computer Scientist, building Innovations to support the local communities in Uganda"
  facebook: Vincent Wayugah
  twitter: Vincent Wayuga
  instagram: Vincent Wayuga
  google_plus: Vincent Wayuga
  linkedin: Vincent Wayuga
  pinterest: Vincent Wayuga
  github: Vincent Wayuga
  keybase: Vincent Wayuga
  street: "First Street"
  locality: Kisumu
  region: central
  postcode: 40100
  country: Kenya

facebook:
  admins: 100001982813077

twitter:
  username:Vincent Wayuga

disqus_shortname: Vincent Wayuga
google_cse_id: 003203019626111314589:pxhon_hlo2q
google_api_key: AIzaSyB27uh5sPHJ156nRryf1yuJn6fjo_B7qvI
google_analytics_id: UA-99335803-1
google_analytics_id_2: UA-99335803-2
language: en

nav:
  - title: Refresh 
  - url: "https://www.covidvisualizer.com/"
  - title: About
    url: "/about/"
  - title: Contact
    url: "/contact/"    
  - title: Books
    url: "/books/"
  - title: Privacy Policy
    url: "/privacy_policy/"
    

repository: azamukedenish/azamukedenish.github.io
branch: master
encoding: utf-8
timezone: Africa/Nairobi
locale: en_us
future: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..3

highlighter: rouge

gist:
  noscript: false

paginate_path: "/writings/page:num/"
paginate: 10

permalink: "/:title/"
defaults:
  - scope:
      path: "https://www.covidvisualizer.com/"
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: "uploads/**/*.pdf"
    values:
      sitemap: false

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development
  profile: false

include:
  - "_pages"

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Gruntfile.js
  - package.json
  - npm-debug.log
  - node_modules
  - vendor
  - bundle
  - ".bundle"
  - ".sass-cache"
  - script
  - src
 
